#!name=Minh Quan
#!desc=Locket Gold

[Script]
locketgold = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/phiminhquan2010/LocketGold/refs/heads/main/gold.js,requires-body=true,max-size=-1,timeout=120
locketgoldheader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/phiminhquan2010/LocketGold/refs/heads/main/header.js,timeout=120
soundcloud = type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/m1nqu4n/SoundCloudGo/refs/heads/main/soundcloud.js

hostname = %APPEND% api.revenuecat.com, api-mobile.soundcloud.com
