#!name=Minh Quan
#!desc=All in One

[Script]
locketgold = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/m1nqu4n/ModuleShadowrocket/refs/heads/main/Script/locketgold.js,requires-body=true,max-size=-1,timeout=120
locketgoldheader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/m1nqu4n/ModuleShadowrocket/refs/heads/main/Script/locketgoldheader.js,timeout=120
soundcloud = type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/m1nqu4n/ModuleShadowrocket/refs/heads/main/Script/soundcloud.js,timeout=120

[MITM]
hostname = %APPEND%, api.revenuecat.com, api-mobile.soundcloud.com
